export const API_BASE_URL = process.env.REACT_APP_API_URL;

export const APP_PATHS = {
  createCooperation: "/Cooperation/create/",
  createDepartment: "/department/create/",
  createVacancies: "/vacancies/create/",
  createEmployees: "/employees/create/",
  createEducation: "/education/create/",
  createShopping: "/shopping/create/",
  changePassword: "/change-password",
  createReports: "/reports/create/",
  createEvents: "/events/create/",
  cooperation: "/Cooperation",
  createNews: "/news/create/",
  learnItems: "/learnItems",
  department: "/department",
  employees: "/employees/",
  vacancies: "/vacancies",
  education: "/education",
  shopping: "/shopping",
  reports: "/reports",
  events: "/events",
  login: "/login",
  home: "/home",
  news: "/news",
};
